name: Test PR

on:
  pull_request:

jobs:
  docs:
    name: "Test"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@main
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-wheel python3-setuptools
          pip install --break-system-packages --upgrade Jinja2
          pip install --break-system-packages --user mkdocs
          pip install --break-system-packages --user $(mkdocs get-deps)
          pip install --break-system-packages --upgrade pygments
          echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
        
      - name: Build Mkdocs
        run: |
          mkdocs build --strict > log 2>&1

      - name: Print Log
        if: always()
        run: |
          cat log
